### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by JaviHer93** [har-in-air/ov7670fifo#1]
Hi, I try to build your code, but I receive the next error:

`/Users/javiher/Documents/esp/ov7670fifo/components/spiffs/./spiffs_vfs.c: In function 'vfs_spiffs_register':
/Users/javiher/Documents/esp/ov7670fifo/components/spiffs/./spiffs_vfs.c:836:9: error: unknown field 'fd_offset' specified in initializ
er
         .fd_offset = 0,
         ^
In file included from /Users/javiher/Documents/esp/ov7670fifo/components/spiffs/./spiffs_vfs.c:24:0:
/Users/javiher/Documents/esp/esp-idf/components/vfs/include/esp_vfs.h:39:37: warning: initialized field overwritten [-Woverride-init]
 #define ESP_VFS_FLAG_DEFAULT        0`

Can you help me with this?

Thank you!

**Comment by har-in-air** [comment]
For option 1, i think you also have to cd to the esp-idf directory after checking out the old commit, and do a 'git submodule update --init'
    On Thursday 25 January 2018, 4:13:13 AM IST, Javier Heredia <notifications@github.com> wrote:  
 
 
Hi, I try to build your code, but I receive the next error:

/Users/javiher/Documents/esp/ov7670fifo/components/spiffs/./spiffs_vfs.c: In function 'vfs_spiffs_register': /Users/javiher/Documents/esp/ov7670fifo/components/spiffs/./spiffs_vfs.c:836:9: error: unknown field 'fd_offset' specified in initializ er .fd_offset = 0, ^ In file included from /Users/javiher/Documents/esp/ov7670fifo/components/spiffs/./spiffs_vfs.c:24:0: /Users/javiher/Documents/esp/esp-idf/components/vfs/include/esp_vfs.h:39:37: warning: initialized field overwritten [-Woverride-init] #define ESP_VFS_FLAG_DEFAULT 0

Can you help me with this?

Thank you!

**Comment by JaviHer93** [comment]
I tried that, but doesn't fix the error. 
What I did, was commented the line of code 836 in the 

> spiffs_vfs.c

 file.
And It worked!

But I really appreciate your help! And your work!

**Comment by JaviHer93** [comment]
Than you!

**Comment by har-in-air** [comment]
Good to know that the fix was that simple!
    On Thursday, 25 January, 2018, 10:20:35 AM IST, Javier Heredia <notifications@github.com> wrote:  
 
 
I tried that, but doesn't fix the error.
What I did, was commented the line of code 836 in the


spiffs_vfs.c


file.
And It worked!

But I really appreciate your help! And your work!
