### ISSUE TITLE
Can run this project

### ISSUE THREAD

**Issue by duy12i1i7** [har-in-air/ov7670fifo#2]
I fail when I run make menuconfig. Plz help me to run this project

**Comment by har-in-air** [comment]
It has been a few years, and I don't even build  esp-idf projects anymore, I use platformio with esp32-arduino framework these days.  So can't help with this, sorry ....

**Comment by duy12i1i7** [comment]
do u have any project like this nowadays? (i mean using platformIO with esp32 framework to deal the same problem)

**Comment by har-in-air** [comment]
no, sorry

**Comment by duy12i1i7** [comment]
Do u remember the version of esp-idf that u deploy the project? I think i cant rerun it because it not fit the version? plz help me to rerun this project

**Comment by har-in-air** [comment]
maybe check the date of the oldest commit to the repository against the esp-idf release dates
    On Monday, 11 December, 2023 at 10:40:51 am IST, Nguyen Dinh Duy ***@***.***> wrote:  
 
 


Do u remember the version of esp-idf that u deploy the project? I think i cant rerun it because it not fit the version? plz help me to rerun this project
